[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
zeroboost = "HW7sPVEXwDyZ7WjmS52dLi6WYiWALnVbSvXYjZ9jErZq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/macbookpro/.config/solana/id.json"

[scripts]
test = "bun x ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
